import "core-js/modules/es6.function.name";
import "core-js/modules/web.dom.iterable";
import Vue from 'vue';
import icon from "./icon";
import tag from "./tag";
import navBar from "./nav-bar";
import tabbar from "./tabbar";
import tabbarItem from "./tabbar-item";
import cell from "./cell";
import cellGroup from "./cell-group";
import timeLine from "./time-line";
import picker from "./picker";
import popup from "./popup";
import Dialog from "./dialog";
var version = '0.1.1';
var components = [icon, tag, navBar, tabbar, tabbarItem, cell, cellGroup, timeLine, picker, popup, Dialog];
components.forEach(function (Component) {
  Vue.component(Component.name, Component);
});
export { version, icon, tag, navBar, tabbar, tabbarItem, cell, cellGroup, timeLine, picker, popup, Dialog };